version: '2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.0
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      bootstrap.memory_lock: "false"
    volumes:
      - .elasticsearch:/usr/share/elasticsearch/data
    network_mode: host
  kibana:
    image: docker.elastic.co/kibana/kibana:6.1.0
    environment:
      ELASTICSEARCH_URL: http://localhost:9200
    network_mode: host
